### ISSUE TITLE
TriplanarSurfaceShader occlusion texture is not being applied.

### ISSUE THREAD

**Issue by Klodrik** [bgolus/Normal-Mapping-for-a-Triplanar-Shader#2]
https://github.com/bgolus/Normal-Mapping-for-a-Triplanar-Shader/blob/1c3ee9b46fabcb94d60646df769241ca70df06a2/TriplanarSurfaceShader.shader#L112

It is using the albedo texture instead of the occlusion texture. colX instead of occX.

half occ = LerpOneTo(occX * triblend.x + occY * triblend.y + occZ * triblend.z, _OcclusionStrength);

**Comment by bgolus** [comment]
Thanks for pointing that out!
